# Generated by Django 5.1.4 on 2025-02-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_entity', models.IntegerField(choices=[(0, 'AEV'), (1, 'APC'), (2, 'CTD'), (3, 'DMA'), (4, 'PVA')])),
                ('station', models.CharField(null=True)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('parameter', models.CharField(choices=[('OX', 'Oxigeno'), ('CL', 'Clorofila'), ('SL', 'Salinidad'), ('TU', 'Turbidez'), ('TR', 'Transparencia')], max_length=255)),
                ('value', models.FloatField()),
                ('units', models.CharField(max_length=10, null=True)),
                ('measure', models.CharField(max_length=10, null=True)),
                ('final_datetime', models.DateTimeField(null=True)),
                ('method', models.CharField(max_length=255, null=True)),
                ('replica', models.IntegerField(max_length=1, null=True)),
                ('depth', models.CharField(choices=[('FONDO', 'FONDO'), ('SUPERFICIE', 'SUPERFICIE')], max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.estacion')),
            ],
        ),
    ]
