# Generated by Django 5.1.4 on 2025-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='parameter',
            field=models.TextField(choices=[('OX', 'Oxigeno'), ('CL', 'Clorofila'), ('SL', 'Salinidad'), ('TU', 'Turbidez'), ('TR', 'Transparencia')], max_length=255),
        ),
    ]
