# Generated by Django 5.1.4 on 2025-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_values_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='replica',
            field=models.IntegerField(null=True),
        ),
    ]
