# Generated by Django 5.1.4 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_values_replica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='parameter',
            field=models.TextField(choices=[('OXIGENO', 'Oxigeno'), ('CLOROFILA', 'Clorofila'), ('SALINIDAD', 'Salinidad'), ('TURBIDEZ', 'Turbidez'), ('TRANSPARENCIA', 'Transparencia'), ('TEMPERATURA', 'Temperatura')], max_length=255),
        ),
    ]
