# Generated by Django 5.1.4 on 2025-03-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Cage'), (1, 'Buoy'), (2, 'LongLine')])),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sensor_type', models.IntegerField(choices=[(0, 'Load'), (1, 'SCL'), (2, 'Floatability'), (3, 'Currentmeter')])),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquamore.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='SensorCorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('heading', models.FloatField(null=True)),
                ('pitch', models.FloatField(null=True)),
                ('roll', models.FloatField(null=True)),
                ('pressure', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('speed1', models.FloatField(null=True)),
                ('direction1', models.FloatField(null=True)),
                ('speed2', models.FloatField(null=True)),
                ('direction2', models.FloatField(null=True)),
                ('speed3', models.FloatField(null=True)),
                ('direction3', models.FloatField(null=True)),
                ('speed4', models.FloatField(null=True)),
                ('direction4', models.FloatField(null=True)),
                ('speed5', models.FloatField(null=True)),
                ('direction5', models.FloatField(null=True)),
                ('speed6', models.FloatField(null=True)),
                ('direction6', models.FloatField(null=True)),
                ('speed7', models.FloatField(null=True)),
                ('direction7', models.FloatField(null=True)),
                ('speed8', models.FloatField(null=True)),
                ('direction8', models.FloatField(null=True)),
                ('speed9', models.FloatField(null=True)),
                ('direction9', models.FloatField(null=True)),
                ('speed10', models.FloatField(null=True)),
                ('direction10', models.FloatField(null=True)),
                ('speed11', models.FloatField(null=True)),
                ('direction11', models.FloatField(null=True)),
                ('speed12', models.FloatField(null=True)),
                ('direction12', models.FloatField(null=True)),
                ('speed13', models.FloatField(null=True)),
                ('direction13', models.FloatField(null=True)),
                ('speed14', models.FloatField(null=True)),
                ('direction14', models.FloatField(null=True)),
                ('speed15', models.FloatField(null=True)),
                ('direction15', models.FloatField(null=True)),
                ('speed16', models.FloatField(null=True)),
                ('direction16', models.FloatField(null=True)),
                ('speed17', models.FloatField(null=True)),
                ('direction17', models.FloatField(null=True)),
                ('speed18', models.FloatField(null=True)),
                ('direction18', models.FloatField(null=True)),
                ('speed19', models.FloatField(null=True)),
                ('direction19', models.FloatField(null=True)),
                ('speed20', models.FloatField(null=True)),
                ('direction20', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquamore.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('weight', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquamore.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorSCLyFlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('depth', models.FloatField(null=True)),
                ('pitch', models.IntegerField(null=True)),
                ('roll', models.IntegerField(null=True)),
                ('head', models.IntegerField(null=True)),
                ('four_p', models.IntegerField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquamore.sensor')),
            ],
        ),
    ]
