# Generated by Django 5.1.4 on 2025-01-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sensor_type', models.IntegerField(choices=[(0, 'Load'), (1, 'SCL')], default=0)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cages.cage')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('weight', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cages.sensor')),
            ],
            options={
                'unique_together': {('sensor', 'date_time')},
            },
        ),
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS pg_cron;
            """,
            reverse_sql="DROP EXTENSION IF EXISTS pg_cron;"
        ),
    ]
