# Generated by Django 5.1.4 on 2025-01-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0001_initial'),
    ]

    operations = [
        # Django considers "id" the primary key of these tables, but
        # we want the primary key to be (sensor_id, id)
        migrations.RunSQL("""
        ALTER TABLE cages_sensorload
        DROP CONSTRAINT cages_sensorload_pkey CASCADE;

        ALTER TABLE cages_sensorload
        ADD CONSTRAINT cages_sensorload_pkey
        PRIMARY KEY (sensor_id, id);
        """),
    ]
